	# Définition du fichier Cloud-init
  data "template_file" "user_data" {
  template = <<EOF
#cloud-config
hostname: ${var.clone_node}
manage_etc_hosts: true

# Définition de l'utilisateur avec droits sudo
users:
  - name: ${var.user_name}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${var.user_password} # Il est préférable d'utiliser un hash
    ssh_authorized_keys:
      - ${trimspace(file("/home/larbin/.ssh/tf_ssh.pub"))}

# Configuration SSH
ssh_pwauth: true
disable_root: true

#packages:
#  - qemu-guest-agent

#runcmd:
#  - systemctl enable qemu-guest-agent
#  - systemctl start qemu-guest-agent
# Forcer la mise à jour de la config SSH par cloud-init
# runcmd:
#   - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config.d/50-cloud-init.conf
#   - systemctl restart ssh
EOF
}
