- name: Installer Docker et EJBCA
  hosts: all
  become: yes
  tasks:
    - name: Installation des dépendances Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        update_cache: yes

    - name: Ajout de la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajout du dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable"
        state: present

    - name: Installation de Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes

    - name: Lancement du conteneur EJBCA Community
      docker_container:
        name: ejbca
        image: keyfactor/ejbca-ce:latest
        state: started
        restart_policy: always
        ports:
          - "80:8080"
          - "443:8443"
        env:
        # Configuration de la DB
          DATABASE_JDBC_URL: "jdbc:h2:/opt/primekey/ejbca/p12/ejbcadb;DB_CLOSE_DELAY=-1"
          INITIAL_ADMIN_KEY_SPEC: "2048"
          # Paramètres d'auto-configuration pour générer le .p12
          NSH_AUTO_CONFIGURE: "true"
          INITIAL_ADMIN_USER: "superadmin"
          INITIAL_ADMIN_PASSWORD: "password"
          INITIAL_CA_NAME: "ManagementCA"
       
    - name: Attendre l'initialisation (génération des certificats)
      pause:
        seconds: 50

    - name: Récupérer le certificat superadmin.p12 sur l'hôte
      shell: "docker cp ejbca:/opt/keyfactor/p12/superadmin.p12 /home/honey/superadmin.p12"
